import {reportRange} from './report-range.js';
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const uuid=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const hash=async text=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const password=async(pass,salt)=>{let k=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveBits']);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},k,256))).map(x=>x.toString(16).padStart(2,'0')).join('')};
const input=(v,max=200)=>typeof v==='string'?v.trim().slice(0,max):'';
const required=(v,max=200)=>input(v,max)||fail('Campo obligatorio');
const one=(db,sql,...p)=>db.prepare(sql).bind(...p).first();
const all=(db,sql,...p)=>db.prepare(sql).bind(...p).all().then(r=>r.results);
const run=(db,sql,...p)=>db.prepare(sql).bind(...p).run();
async function auth(req,db){let token=req.headers.get('authorization')?.replace(/^Bearer /i,'');if(!token)return null;return one(db,`SELECT u.id,u.name,u.username,u.role_id,u.active,s.id session_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`,await hash(token),now()).then(x=>x?.active?x:null)}
async function perms(db,user){return user?new Set((await all(db,'SELECT permission FROM role_permissions WHERE role_id=?',user.role_id)).map(x=>x.permission)):new Set()}
const has=(p,s)=>p.has(s)||p.has('*');
const need=(p,s)=>{if(!has(p,s))fail('Sin permiso',403)};
async function body(req){let b;try{b=await req.json()}catch{fail('JSON inválido')}if(!b||typeof b!=='object'||Array.isArray(b))fail('Datos inválidos');return b}
function cors(req,env){let origin=req.headers.get('origin');let allowed=(env.ALLOWED_ORIGIN||'').split(',').map(x=>x.trim());return origin&&allowed.includes(origin)?{'access-control-allow-origin':origin,'vary':'Origin','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS'}:{}}
async function visible(db,u,p,id){if(has(p,'dispatch.read.all'))return true;if(id===u.id)return true;return !!await one(db,'SELECT 1 FROM user_visibility WHERE user_id=? AND seller_id=?',u.id,id)}
async function detail(db,u,p,id){let d=await one(db,'SELECT * FROM dispatches WHERE id=?',id);if(!d)fail('Despacho inexistente',404);if(!await visible(db,u,p,d.seller_id))fail('Sin permiso',403);d.items=await all(db,'SELECT * FROM dispatch_items WHERE dispatch_id=? ORDER BY rowid',id);return d}
const models={categories:{fields:['name','sort_order','active'],perm:'catalog.manage'},customers:{fields:['name','phone','direction','notes'],perm:'customers.manage'}};
const productSelect=`SELECT p.*,v.family_id,v.name variety_name,f.name family_name,COALESCE(f.name||' · '||v.name||' · '||p.packaging,p.name) display_name FROM products p LEFT JOIN product_varieties v ON v.id=p.variety_id LEFT JOIN product_families f ON f.id=v.family_id`;
function order(value){let n=Number(value);if(!Number.isSafeInteger(n)||n<0||n>1000000)fail('Orden inválido');return n}
function weight(value){if(value===undefined||value===null||value==='')return null;let n=Number(value);if(!Number.isFinite(n)||n<=0||n>1000000||Math.abs(Math.round(n*1000)-n*1000)>1e-6)fail('Peso por unidad inválido (kg, hasta 3 decimales)');return n}
async function handler(req,env){const db=env.DB,url=new URL(req.url),path=url.pathname.replace(/^\/api\/v1/,'').split('/').filter(Boolean),method=req.method;
if(!url.pathname.startsWith('/api/v1/'))fail('Ruta inexistente',404);
if(path[0]==='setup'&&method==='POST'){
 if(await one(db,'SELECT 1 FROM users LIMIT 1'))fail('Ya inicializada',409);
 let b=await body(req),name=required(b.name),username=required(b.username,80).toLowerCase(),pass=required(b.password,500);if(pass.length<12)fail('Contraseña mínima: 12 caracteres');let salt=uuid(),id=uuid(),t=now();await run(db,'INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?)',id,name,username,await password(pass,salt),salt,'superadmin',1,t,t);return json({ok:true},201)
}
if(path[0]==='login'&&method==='POST'){let b=await body(req),u=await one(db,'SELECT * FROM users WHERE username=? AND active=1',input(b.username,80).toLowerCase());if(!u||await password(String(b.password||''),u.salt)!==u.password_hash)fail('Credenciales inválidas',401);let token=uuid()+uuid(),t=now();await run(db,'INSERT INTO sessions VALUES(?,?,?,?,?)',uuid(),u.id,await hash(token),new Date(Date.now()+7*864e5).toISOString(),t);return json({token,user:{id:u.id,name:u.name,role:u.role_id}})}
let u=await auth(req,db);if(!u)fail('Iniciá sesión',401);let p=await perms(db,u);
if(path[0]==='me')return json({user:{id:u.id,name:u.name,role:u.role_id},permissions:[...p]});
if(path[0]==='logout'&&method==='POST'){await run(db,'DELETE FROM sessions WHERE id=?',u.session_id);return json({ok:true})}
if(path[0]==='roles'){
 if(method==='GET')return json(await all(db,'SELECT r.id,r.name,group_concat(rp.permission) permissions FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id GROUP BY r.id'));
 need(p,'roles.manage');let b=await body(req),id=input(b.id,80)||uuid(),name=required(b.name,80);if(!/^[a-z0-9_-]+$/.test(id))fail('ID inválido');let permissions=Array.isArray(b.permissions)?b.permissions:[];let valid=new Set((await all(db,'SELECT name FROM permissions')).map(x=>x.name));if(permissions.some(x=>!valid.has(x)))fail('Permiso inválido');let stm=[db.prepare('INSERT INTO roles VALUES(?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name').bind(id,name),db.prepare('DELETE FROM role_permissions WHERE role_id=?').bind(id),...permissions.map(x=>db.prepare('INSERT INTO role_permissions VALUES(?,?)').bind(id,x))];await db.batch(stm);return json({id})
}
if(path[0]==='permissions')return json(await all(db,'SELECT name FROM permissions'));
if(path[0]==='users'){
 need(p,'users.manage');if(method==='GET')return json(await all(db,'SELECT id,name,username,role_id,active,created_at,updated_at FROM users ORDER BY name'));
 let b=await body(req);if(method==='POST'){let name=required(b.name),username=required(b.username,80).toLowerCase(),pass=required(b.password,500),role=required(b.role_id,80);if(pass.length<12)fail('Contraseña mínima: 12 caracteres');if(!await one(db,'SELECT 1 FROM roles WHERE id=?',role))fail('Rol inexistente');if(role==='superadmin'&&!has(p,'roles.manage'))fail('Sin permiso',403);let id=uuid(),salt=uuid(),t=now();await run(db,'INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?)',id,name,username,await password(pass,salt),salt,role,1,t,t);return json({id},201)}
 if(method==='PUT'&&path[1]){let old=await one(db,'SELECT * FROM users WHERE id=?',path[1]);if(!old)fail('Usuario inexistente',404);if((old.role_id==='superadmin'||b.role_id==='superadmin')&&!has(p,'roles.manage'))fail('Sin permiso',403);let role=input(b.role_id,80)||old.role_id;if(!await one(db,'SELECT 1 FROM roles WHERE id=?',role))fail('Rol inexistente');let active=b.active===undefined?old.active:b.active?1:0;if(old.id===u.id&&!active)fail('No podés desactivarte');let name=input(b.name)||old.name;await run(db,'UPDATE users SET name=?,role_id=?,active=?,updated_at=? WHERE id=?',name,role,active,now(),old.id);if(b.password){if(String(b.password).length<12)fail('Contraseña mínima: 12 caracteres');let salt=uuid();await run(db,'UPDATE users SET salt=?,password_hash=? WHERE id=?',salt,await password(b.password,salt),old.id);await run(db,'DELETE FROM sessions WHERE user_id=?',old.id)}return json({id:old.id})}
 if(method==='DELETE'&&path[1]){if(path[1]===u.id)fail('No podés desactivarte');await run(db,'UPDATE users SET active=0,updated_at=? WHERE id=?',now(),path[1]);return json({ok:true})}
}
if(path[0]==='visibility'){need(p,'users.manage');if(method==='GET')return json(await all(db,'SELECT * FROM user_visibility'));if(method==='PUT'&&path[1]){let b=await body(req);if(!Array.isArray(b.sellers))fail('Lista inválida');let valid=await all(db,`SELECT id FROM users WHERE id IN (${b.sellers.map(()=>'?').join(',')||"''"})`,...b.sellers);if(valid.length!==new Set(b.sellers).size)fail('Vendedor inexistente');await db.batch([db.prepare('DELETE FROM user_visibility WHERE user_id=?').bind(path[1]),...b.sellers.map(id=>db.prepare('INSERT INTO user_visibility VALUES(?,?)').bind(path[1],id))]);return json({ok:true})}}
if(path[0]==='settings'){if(method==='GET')return json(JSON.parse((await one(db,"SELECT value FROM settings WHERE key='issuer'")).value));need(p,'settings.manage');let b=await body(req),issuer={name:input(b.name),logo:input(b.logo,200000),direction:input(b.direction),phone:input(b.phone),extra:input(b.extra,1000)};if(issuer.logo&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(issuer.logo))fail('Logo inválido');await run(db,"UPDATE settings SET value=? WHERE key='issuer'",JSON.stringify(issuer));return json(issuer)}
if(path[0]==='salespeople'||path[0]==='carriers'){
 const sales=path[0]==='salespeople',table=sales?'salespeople':'carriers';
 if(method==='GET')return json(await all(db,`SELECT * FROM ${table} ORDER BY first_name,last_name`));
 need(p,'settings.manage');
 if(method==='DELETE'&&path[1]){let result=await run(db,`UPDATE ${table} SET active=0,updated_at=? WHERE id=?`,now(),path[1]);if(!result.meta.changes)fail('No encontrado',404);return json({ok:true})}
 if(method!=='POST'&&method!=='PUT')fail('Método inválido',405);
 let b=await body(req),id=path[1]||uuid(),t=now(),first=required(b.first_name,100),last=required(b.last_name,100),active=b.active===false||b.active===0?0:1;
 let extra=sales?[input(b.whatsapp,50)||null,input(b.alternate_phone,50)||null,input(b.email,200)||null]:[required(b.vehicle,120),required(b.plate,30),required(b.ownership,20)];
 if(sales&&extra[2]&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(extra[2]))fail('Email inválido');
 if(!sales&&!['PROPIO','TERCERO'].includes(extra[2]))fail('Tipo de transportista inválido');
 let fields=sales?'whatsapp,alternate_phone,email':'vehicle,plate,ownership';
 if(method==='POST'){await run(db,`INSERT INTO ${table}(id,first_name,last_name,${fields},active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`,id,first,last,...extra,active,t,t);return json({id},201)}
 let result=await run(db,`UPDATE ${table} SET first_name=?,last_name=?,${fields.split(',').map(f=>f+'=?').join(',')},active=?,updated_at=? WHERE id=?`,first,last,...extra,active,t,id);
 if(!result.meta.changes)fail('No encontrado',404);return json({id})
}
if(path[0]==='families'||path[0]==='varieties'){
 let family=path[0]==='families',table=family?'product_families':'product_varieties';
 if(method==='GET')return json(await all(db,`SELECT * FROM ${table} ORDER BY ${family?'sort_order,name':'family_id,sort_order,name'}`));
 need(p,'catalog.manage');if(method!=='POST'&&method!=='PUT')fail('Método inválido',405);
 let b=await body(req),id=path[1]||uuid(),name=required(b.name,120),sort=order(b.sort_order??0),active=b.active===false||b.active===0?0:1,t=now(),familyId=null;
 if(!family){familyId=required(b.family_id,80);if(!await one(db,'SELECT 1 FROM product_families WHERE id=?',familyId))fail('Producto base inexistente')}
 if(await one(db,`SELECT 1 FROM ${table} WHERE name=? ${family?'':'AND family_id=?'} AND id<>?`,...(family?[name,id]:[name,familyId,id])))fail('Ya existe ese nombre',409);
 if(method==='POST'){await run(db,`INSERT INTO ${table}(${family?'id,name,active,sort_order,created_at,updated_at':'id,family_id,name,active,sort_order,created_at,updated_at'}) VALUES(${family?'?,?,?,?,?,?':'?,?,?,?,?,?,?'})`,...(family?[id,name,active,sort,t,t]:[id,familyId,name,active,sort,t,t]));return json({id},201)}
 let result=await run(db,`UPDATE ${table} SET ${family?'name=?,active=?,sort_order=?,updated_at=?':'family_id=?,name=?,active=?,sort_order=?,updated_at=?'} WHERE id=?`,...(family?[name,active,sort,t,id]:[familyId,name,active,sort,t,id]));if(!result.meta.changes)fail('No encontrado',404);return json({id})
}
if(path[0]==='products'){
 if(method==='GET'){if(path[1]){let item=await one(db,productSelect+' WHERE p.id=?',path[1]);if(!item)fail('No encontrado',404);return json(item)}return json(await all(db,productSelect+' ORDER BY p.sort_order,p.name'))}
 need(p,'catalog.manage');if(method==='DELETE'&&path[1]){await run(db,'UPDATE products SET active=0,updated_at=? WHERE id=?',now(),path[1]);return json({ok:true})}
 if(method!=='POST'&&method!=='PUT')fail('Método inválido',405);
 let b=await body(req),old=path[1]?await one(db,'SELECT * FROM products WHERE id=?',path[1]):null;
 if(path[1]&&!old)fail('Presentación inexistente',404);
 let varietyId=input(b.variety_id,80)||null,packaging=input(b.packaging,120)||null;
 if(!varietyId&&!old)fail('Elegí una variedad');if(varietyId&&!packaging)fail('Ingresá un empaque');
 if(varietyId&&!await one(db,'SELECT 1 FROM product_varieties WHERE id=?',varietyId))fail('Variedad inexistente');
 if(varietyId&&await one(db,'SELECT 1 FROM products WHERE variety_id=? AND packaging=? AND id<>?',varietyId,packaging,path[1]||''))fail('Ya existe ese empaque en la variedad',409);
 let names=varietyId?await one(db,'SELECT f.name family,v.name variety FROM product_varieties v JOIN product_families f ON f.id=v.family_id WHERE v.id=?',varietyId):null,name=names?`${names.family} · ${names.variety} · ${packaging}`:required(b.name),category=input(b.category_id,80)||null,unit=input(b.unit,80)||'unidad',active=b.active===false||b.active===0?0:1,sort=order(b.sort_order??0),mass=weight(b.weight_kg),t=now();
 if(category&&!await one(db,'SELECT 1 FROM categories WHERE id=?',category))fail('Categoría inexistente');
 if(method==='POST'){let id=uuid();await run(db,'INSERT INTO products(id,name,category_id,unit,weight_kg,sort_order,active,variety_id,packaging,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,name,category,unit,mass,sort,active,varietyId,packaging,t,t);return json({id},201)}
 await run(db,'UPDATE products SET name=?,category_id=?,unit=?,weight_kg=?,sort_order=?,active=?,variety_id=?,packaging=?,updated_at=? WHERE id=?',name,category,unit,mass,sort,active,varietyId,packaging,t,path[1]);return json({id:path[1]})
}
let model=models[path[0]];if(model){if(method==='GET'){if(path[1]){let x=await one(db,`SELECT * FROM ${path[0]} WHERE id=?`,path[1]);if(!x)fail('No encontrado',404);return json(x)}return json(await all(db,`SELECT * FROM ${path[0]} ORDER BY ${path[0]==='customers'?'name':'sort_order,name'}`))}need(p,model.perm);if(method==='DELETE'&&path[1]){if(path[0]==='customers')fail('Conservar clientes históricos',409);await run(db,`UPDATE ${path[0]} SET active=0,updated_at=? WHERE id=?`,now(),path[1]);return json({ok:true})}let b=await body(req),id=path[1]||uuid(),t=now();let vals={};for(let f of model.fields){if(f==='name')vals[f]=required(b[f]);else if(f==='active')vals[f]=b[f]===false||b[f]===0?0:1;else if(f==='sort_order')vals[f]=Number.isInteger(Number(b[f]))?Number(b[f]):0;else if(f==='weight_kg'){let raw=b[f],weight=Number(raw);if(raw===undefined||raw===null||raw==='')vals[f]=null;else{if(!Number.isFinite(weight)||weight<=0||weight>1000000||Math.abs(Math.round(weight*1000)-weight*1000)>1e-6)fail('Peso por unidad inválido (kg, hasta 3 decimales)');vals[f]=weight}}else vals[f]=input(b[f],500)||null}if(path[0]==='products')vals.unit=vals.unit||'unidad';if(path[0]==='products'&&vals.category_id&&!await one(db,'SELECT 1 FROM categories WHERE id=?',vals.category_id))fail('Categoría inexistente');if(method==='POST'){await run(db,`INSERT INTO ${path[0]}(id,${model.fields.join(',')},created_at,updated_at) VALUES(?,${model.fields.map(()=>'?').join(',')},?,?)`,id,...model.fields.map(f=>vals[f]),t,t);return json({id},201)}if(method==='PUT'&&path[1]){let result=await run(db,`UPDATE ${path[0]} SET ${model.fields.map(f=>f+'=?').join(',')},updated_at=? WHERE id=?`,...model.fields.map(f=>vals[f]),t,id);if(!result.meta.changes)fail('No encontrado',404);return json({id})}}
if(path[0]==='reports'&&path[1]==='customer'&&method==='GET'){
 let customerId=url.searchParams.get('customer_id'),from=url.searchParams.get('from'),to=url.searchParams.get('to');
 if(!customerId)fail('Elegí cliente');let range=reportRange(from,to);if(!range)fail('Elegí un rango de fechas válido');
 let customer=await one(db,'SELECT id,name,phone,direction FROM customers WHERE id=?',customerId);if(!customer)fail('Cliente inexistente',404);
 let scope=`d.customer_id=? AND d.status='CONFIRMADO' AND d.confirmed_at>=? AND d.confirmed_at<? AND (d.seller_id=? OR EXISTS(SELECT 1 FROM user_visibility v WHERE v.user_id=? AND v.seller_id=d.seller_id) OR ?=1)`;
 let args=[customerId,range.start,range.end,u.id,u.id,has(p,'dispatch.read.all')?1:0];
 let totals=await one(db,`SELECT COUNT(DISTINCT d.id) dispatches,COUNT(DISTINCT COALESCE(i.variety_id,i.product_id)) variety,COUNT(DISTINCT i.product_id) presentations,COALESCE(SUM(COALESCE(i.units_count,i.quantity)),0) units,ROUND(COALESCE(SUM(i.weight_kg),0),3) weight_kg,COALESCE(SUM(CASE WHEN i.weight_kg IS NULL THEN 1 ELSE 0 END),0) unknown_weight_lines FROM dispatches d JOIN dispatch_items i ON i.dispatch_id=d.id WHERE ${scope}`,...args);
 let products=await all(db,`SELECT i.product_id,MIN(i.product_name) name,COUNT(DISTINCT d.id) dispatches,SUM(COALESCE(i.units_count,i.quantity)) units,ROUND(COALESCE(SUM(i.weight_kg),0),3) weight_kg,SUM(CASE WHEN i.weight_kg IS NULL THEN 1 ELSE 0 END) unknown_weight_lines FROM dispatches d JOIN dispatch_items i ON i.dispatch_id=d.id WHERE ${scope} GROUP BY i.product_id ORDER BY units DESC,name`,...args);
 return json({customer,from,to,totals,products})
}
if(path[0]==='dispatches'){
 if(method==='GET'&&!path[1]){let q=`SELECT d.* FROM dispatches d WHERE (d.seller_id=? OR EXISTS(SELECT 1 FROM user_visibility v WHERE v.user_id=? AND v.seller_id=d.seller_id) OR ?=1)`,v=[u.id,u.id,has(p,'dispatch.read.all')?1:0];for(let [key,col] of [['number','d.number'],['customer','d.customer_name'],['seller','d.seller_id'],['status','d.status']]){let value=url.searchParams.get(key);if(value){q+=` AND ${col} ${key==='number'||key==='seller'||key==='status'?'=':'LIKE' } ?`;v.push(key==='customer'?`%${value}%`:value)}}for(let [key,op] of [['from','>='],['to','<=']]){let x=url.searchParams.get(key);if(x){q+=` AND d.created_at ${op} ?`;v.push(x+(key==='to'?'T23:59:59.999Z':''))}}let product=url.searchParams.get('product');if(product){q+=' AND EXISTS(SELECT 1 FROM dispatch_items i WHERE i.dispatch_id=d.id AND i.product_name LIKE ?)';v.push('%'+product+'%')}q+=' ORDER BY d.created_at DESC LIMIT 100';return json(await all(db,q,...v))}
 if(method==='GET'&&path[1])return json(await detail(db,u,p,path[1]));
 if(method==='POST'&&!path[1]){need(p,'dispatch.create');let b=await body(req),customer=await one(db,'SELECT * FROM customers WHERE id=?',b.customer_id);if(!customer)fail('Cliente inexistente');if(!Array.isArray(b.items)||!b.items.length||b.items.length>100)fail('Seleccioná productos');let unique=new Set(b.items.map(x=>x.product_id));if(unique.size!==b.items.length)fail('Producto repetido');let products=[];for(let i of b.items){let x=await one(db,productSelect+' WHERE p.id=? AND p.active=1 AND (p.variety_id IS NULL OR (v.active=1 AND f.active=1))',i.product_id);if(!x)fail('Producto no disponible');let units=Number(i.units_count);if(!Number.isSafeInteger(units)||units<=0||units>1000000)fail('Unidades inválidas');if(x.weight_kg===null||x.weight_kg===undefined)fail('Configurá el peso por unidad de '+x.name+' en Productos');products.push({...x,units_count:units,total_weight_kg:Math.round(x.weight_kg*units*1000)/1000})}let salesperson=b.salesperson_id?await one(db,'SELECT * FROM salespeople WHERE id=? AND active=1',b.salesperson_id):null,carrier=b.carrier_id?await one(db,'SELECT * FROM carriers WHERE id=? AND active=1',b.carrier_id):null;
 if(b.salesperson_id&&!salesperson)fail('Vendedor inexistente o inactivo');if(b.carrier_id&&!carrier)fail('Transportista inexistente o inactivo');
 let id=uuid(),t=now(),issuer=(await one(db,"SELECT value FROM settings WHERE key='issuer'")).value;await db.batch([db.prepare('INSERT INTO dispatches(id,customer_id,customer_name,seller_id,seller_name,status,reference,notes,created_by,created_at,updated_at,issuer_snapshot,customer_phone,customer_direction,salesperson_id,salesperson_name,carrier_id,carrier_name) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,customer.id,customer.name,u.id,u.name,'BORRADOR',input(b.reference,200),input(b.notes,1000),u.id,t,t,issuer,customer.phone,customer.direction,salesperson?.id||null,salesperson?`${salesperson.first_name} ${salesperson.last_name}`:null,carrier?.id||null,carrier?`${carrier.first_name} ${carrier.last_name}`:null),...products.map(x=>db.prepare('INSERT INTO dispatch_items(id,dispatch_id,product_id,product_name,unit,quantity,units_count,weight_kg,weight_per_unit_kg,variety_id) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(uuid(),id,x.id,x.display_name,x.unit,x.units_count,x.units_count,x.total_weight_kg,x.weight_kg,x.variety_id))]);return json({id},201)}
 if(method==='POST'&&path[2]==='confirm'){let d=await detail(db,u,p,path[1]);if(d.seller_id!==u.id&&!has(p,'dispatch.read.all'))fail('Sin permiso',403);if(d.status!=='BORRADOR')fail('Estado inválido',409);let result=await db.batch([db.prepare('UPDATE dispatch_counter SET next_number=next_number+1 WHERE id=1 RETURNING next_number-1 AS number'),db.prepare("UPDATE dispatches SET status='CONFIRMADO',number=(SELECT next_number-1 FROM dispatch_counter WHERE id=1),confirmed_by=?,confirmed_at=?,updated_at=? WHERE id=? AND status='BORRADOR'").bind(u.id,now(),now(),d.id)]);return json({id:d.id,number:result[0].results[0].number})}
 if(method==='POST'&&path[2]==='void'){need(p,'dispatch.void');let d=await detail(db,u,p,path[1]);if(d.status!=='CONFIRMADO')fail('Estado inválido',409);await run(db,"UPDATE dispatches SET status='ANULADO',voided_by=?,voided_at=?,updated_at=? WHERE id=?",u.id,now(),now(),d.id);return json({ok:true})}
}
fail('Ruta inexistente',404)}
export default {async fetch(req,env){let c=cors(req,env);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:c});try{let r=await handler(req,env);Object.entries(c).forEach(([k,v])=>r.headers.set(k,v));r.headers.set('cache-control','no-store');return r}catch(e){if(!e.status)console.error('EfraApp Worker error',e);return json({error:e.status?e.message:'Error interno'},e.status||500,c)}}};
