const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const uuid=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const hash=async text=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const password=async(pass,salt)=>{let k=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveBits']);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:210000,hash:'SHA-256'},k,256))).map(x=>x.toString(16).padStart(2,'0')).join('')};
const input=(v,max=200)=>typeof v==='string'?v.trim().slice(0,max):'';
const required=(v,max=200)=>input(v,max)||fail('Campo obligatorio');
const one=(db,sql,...p)=>db.prepare(sql).bind(...p).first();
const all=(db,sql,...p)=>db.prepare(sql).bind(...p).all().then(r=>r.results);
const run=(db,sql,...p)=>db.prepare(sql).bind(...p).run();
async function auth(req,db){let token=req.headers.get('authorization')?.replace(/^Bearer /i,'');if(!token)return null;return one(db,`SELECT u.id,u.name,u.username,u.role_id,u.active,s.id session_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`,await hash(token),now()).then(x=>x?.active?x:null)}
async function perms(db,user){return user?new Set((await all(db,'SELECT permission FROM role_permissions WHERE role_id=?',user.role_id)).map(x=>x.permission)):new Set()}
const has=(p,s)=>p.has(s)||p.has('*');
const need=(p,s)=>{if(!has(p,s))fail('Sin permiso',403)};
async function body(req){let b;try{b=await req.json()}catch{fail('JSON inválido')}if(!b||typeof b!=='object'||Array.isArray(b))fail('Datos inválidos');return b}
function cors(req,env){let origin=req.headers.get('origin');let allowed=(env.ALLOWED_ORIGIN||'').split(',').map(x=>x.trim());return origin&&allowed.includes(origin)?{'access-control-allow-origin':origin,'vary':'Origin','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS'}:{}}
async function visible(db,u,p,id){if(has(p,'dispatch.read.all'))return true;if(id===u.id)return true;return !!await one(db,'SELECT 1 FROM user_visibility WHERE user_id=? AND seller_id=?',u.id,id)}
async function detail(db,u,p,id){let d=await one(db,'SELECT * FROM dispatches WHERE id=?',id);if(!d)fail('Despacho inexistente',404);if(!await visible(db,u,p,d.seller_id))fail('Sin permiso',403);d.items=await all(db,'SELECT * FROM dispatch_items WHERE dispatch_id=? ORDER BY rowid',id);return d}
const models={categories:{fields:['name','sort_order','active'],perm:'catalog.manage'},products:{fields:['name','category_id','unit','sort_order','active'],perm:'catalog.manage'},customers:{fields:['name','phone','direction','notes'],perm:'customers.manage'}};
async function handler(req,env){const db=env.DB,url=new URL(req.url),path=url.pathname.replace(/^\/api\/v1/,'').split('/').filter(Boolean),method=req.method;
if(!url.pathname.startsWith('/api/v1/'))fail('Ruta inexistente',404);
if(path[0]==='setup'&&method==='POST'){
 if(await one(db,'SELECT 1 FROM users LIMIT 1'))fail('Ya inicializada',409);
 let b=await body(req),name=required(b.name),username=required(b.username,80).toLowerCase(),pass=required(b.password,500);if(pass.length<12)fail('Contraseña mínima: 12 caracteres');let salt=uuid(),id=uuid(),t=now();await run(db,'INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?)',id,name,username,await password(pass,salt),salt,'superadmin',1,t,t);return json({ok:true},201)
}
if(path[0]==='login'&&method==='POST'){let b=await body(req),u=await one(db,'SELECT * FROM users WHERE username=? AND active=1',input(b.username,80).toLowerCase());if(!u||await password(String(b.password||''),u.salt)!==u.password_hash)fail('Credenciales inválidas',401);let token=uuid()+uuid(),t=now();await run(db,'INSERT INTO sessions VALUES(?,?,?,?,?)',uuid(),u.id,await hash(token),new Date(Date.now()+7*864e5).toISOString(),t);return json({token,user:{id:u.id,name:u.name,role:u.role_id}})}
let u=await auth(req,db);if(!u)fail('Iniciá sesión',401);let p=await perms(db,u);
if(path[0]==='me')return json({user:{id:u.id,name:u.name,role:u.role_id},permissions:[...p]});
if(path[0]==='logout'&&method==='POST'){await run(db,'DELETE FROM sessions WHERE id=?',u.session_id);return json({ok:true})}
if(path[0]==='roles'){
 if(method==='GET')return json(await all(db,'SELECT r.id,r.name,group_concat(rp.permission) permissions FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id GROUP BY r.id'));
 need(p,'roles.manage');let b=await body(req),id=input(b.id,80)||uuid(),name=required(b.name,80);if(!/^[a-z0-9_-]+$/.test(id))fail('ID inválido');let permissions=Array.isArray(b.permissions)?b.permissions:[];let valid=new Set((await all(db,'SELECT name FROM permissions')).map(x=>x.name));if(permissions.some(x=>!valid.has(x)))fail('Permiso inválido');let stm=[db.prepare('INSERT INTO roles VALUES(?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name').bind(id,name),db.prepare('DELETE FROM role_permissions WHERE role_id=?').bind(id),...permissions.map(x=>db.prepare('INSERT INTO role_permissions VALUES(?,?)').bind(id,x))];await db.batch(stm);return json({id})
}
if(path[0]==='permissions')return json(await all(db,'SELECT name FROM permissions'));
if(path[0]==='users'){
 need(p,'users.manage');if(method==='GET')return json(await all(db,'SELECT id,name,username,role_id,active,created_at,updated_at FROM users ORDER BY name'));
 let b=await body(req);if(method==='POST'){let name=required(b.name),username=required(b.username,80).toLowerCase(),pass=required(b.password,500),role=required(b.role_id,80);if(pass.length<12)fail('Contraseña mínima: 12 caracteres');if(!await one(db,'SELECT 1 FROM roles WHERE id=?',role))fail('Rol inexistente');if(role==='superadmin'&&!has(p,'roles.manage'))fail('Sin permiso',403);let id=uuid(),salt=uuid(),t=now();await run(db,'INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?)',id,name,username,await password(pass,salt),salt,role,1,t,t);return json({id},201)}
 if(method==='PUT'&&path[1]){let old=await one(db,'SELECT * FROM users WHERE id=?',path[1]);if(!old)fail('Usuario inexistente',404);if((old.role_id==='superadmin'||b.role_id==='superadmin')&&!has(p,'roles.manage'))fail('Sin permiso',403);let role=input(b.role_id,80)||old.role_id;if(!await one(db,'SELECT 1 FROM roles WHERE id=?',role))fail('Rol inexistente');let active=b.active===undefined?old.active:b.active?1:0;if(old.id===u.id&&!active)fail('No podés desactivarte');let name=input(b.name)||old.name;await run(db,'UPDATE users SET name=?,role_id=?,active=?,updated_at=? WHERE id=?',name,role,active,now(),old.id);if(b.password){if(String(b.password).length<12)fail('Contraseña mínima: 12 caracteres');let salt=uuid();await run(db,'UPDATE users SET salt=?,password_hash=? WHERE id=?',salt,await password(b.password,salt),old.id);await run(db,'DELETE FROM sessions WHERE user_id=?',old.id)}return json({id:old.id})}
 if(method==='DELETE'&&path[1]){if(path[1]===u.id)fail('No podés desactivarte');await run(db,'UPDATE users SET active=0,updated_at=? WHERE id=?',now(),path[1]);return json({ok:true})}
}
if(path[0]==='visibility'){need(p,'users.manage');if(method==='GET')return json(await all(db,'SELECT * FROM user_visibility'));if(method==='PUT'&&path[1]){let b=await body(req);if(!Array.isArray(b.sellers))fail('Lista inválida');let valid=await all(db,`SELECT id FROM users WHERE id IN (${b.sellers.map(()=>'?').join(',')||"''"})`,...b.sellers);if(valid.length!==new Set(b.sellers).size)fail('Vendedor inexistente');await db.batch([db.prepare('DELETE FROM user_visibility WHERE user_id=?').bind(path[1]),...b.sellers.map(id=>db.prepare('INSERT INTO user_visibility VALUES(?,?)').bind(path[1],id))]);return json({ok:true})}}
if(path[0]==='settings'){if(method==='GET')return json(JSON.parse((await one(db,"SELECT value FROM settings WHERE key='issuer'")).value));need(p,'settings.manage');let b=await body(req),issuer={name:input(b.name),logo:input(b.logo,200000),direction:input(b.direction),phone:input(b.phone),extra:input(b.extra,1000)};if(issuer.logo&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(issuer.logo))fail('Logo inválido');await run(db,"UPDATE settings SET value=? WHERE key='issuer'",JSON.stringify(issuer));return json(issuer)}
let model=models[path[0]];if(model){if(method==='GET'){if(path[1]){let x=await one(db,`SELECT * FROM ${path[0]} WHERE id=?`,path[1]);if(!x)fail('No encontrado',404);return json(x)}return json(await all(db,`SELECT * FROM ${path[0]} ORDER BY ${path[0]==='customers'?'name':'sort_order,name'}`))}need(p,model.perm);if(method==='DELETE'&&path[1]){if(path[0]==='customers')fail('Conservar clientes históricos',409);await run(db,`UPDATE ${path[0]} SET active=0,updated_at=? WHERE id=?`,now(),path[1]);return json({ok:true})}let b=await body(req),id=path[1]||uuid(),t=now();let vals={};for(let f of model.fields){if(f==='name')vals[f]=required(b[f]);else if(f==='active')vals[f]=b[f]===false||b[f]===0?0:1;else if(f==='sort_order')vals[f]=Number.isInteger(Number(b[f]))?Number(b[f]):0;else vals[f]=input(b[f],500)||null}if(path[0]==='products')vals.unit=vals.unit||'unidad';if(path[0]==='products'&&vals.category_id&&!await one(db,'SELECT 1 FROM categories WHERE id=?',vals.category_id))fail('Categoría inexistente');if(method==='POST'){await run(db,`INSERT INTO ${path[0]}(id,${model.fields.join(',')},created_at,updated_at) VALUES(?,${model.fields.map(()=>'?').join(',')},?,?)`,id,...model.fields.map(f=>vals[f]),t,t);return json({id},201)}if(method==='PUT'&&path[1]){let result=await run(db,`UPDATE ${path[0]} SET ${model.fields.map(f=>f+'=?').join(',')},updated_at=? WHERE id=?`,...model.fields.map(f=>vals[f]),t,id);if(!result.meta.changes)fail('No encontrado',404);return json({id})}}
if(path[0]==='dispatches'){
 if(method==='GET'&&!path[1]){let q=`SELECT d.* FROM dispatches d WHERE (d.seller_id=? OR EXISTS(SELECT 1 FROM user_visibility v WHERE v.user_id=? AND v.seller_id=d.seller_id) OR ?=1)`,v=[u.id,u.id,has(p,'dispatch.read.all')?1:0];for(let [key,col] of [['number','d.number'],['customer','d.customer_name'],['seller','d.seller_id'],['status','d.status']]){let value=url.searchParams.get(key);if(value){q+=` AND ${col} ${key==='number'||key==='seller'||key==='status'?'=':'LIKE' } ?`;v.push(key==='customer'?`%${value}%`:value)}}for(let [key,op] of [['from','>='],['to','<=']]){let x=url.searchParams.get(key);if(x){q+=` AND d.created_at ${op} ?`;v.push(x+(key==='to'?'T23:59:59.999Z':''))}}let product=url.searchParams.get('product');if(product){q+=' AND EXISTS(SELECT 1 FROM dispatch_items i WHERE i.dispatch_id=d.id AND i.product_name LIKE ?)';v.push('%'+product+'%')}q+=' ORDER BY d.created_at DESC LIMIT 100';return json(await all(db,q,...v))}
 if(method==='GET'&&path[1])return json(await detail(db,u,p,path[1]));
 if(method==='POST'&&!path[1]){need(p,'dispatch.create');let b=await body(req),customer=await one(db,'SELECT * FROM customers WHERE id=?',b.customer_id);if(!customer)fail('Cliente inexistente');if(!Array.isArray(b.items)||!b.items.length||b.items.length>100)fail('Seleccioná productos');let unique=new Set(b.items.map(x=>x.product_id));if(unique.size!==b.items.length)fail('Producto repetido');let products=[];for(let i of b.items){let x=await one(db,'SELECT * FROM products WHERE id=? AND active=1',i.product_id);if(!x)fail('Producto no disponible');let qty=Number(i.quantity);if(!Number.isFinite(qty)||qty<=0||qty>1e6)fail('Cantidad inválida');products.push({...x,quantity:qty})}let id=uuid(),t=now(),issuer=(await one(db,"SELECT value FROM settings WHERE key='issuer'")).value;await db.batch([db.prepare('INSERT INTO dispatches(id,customer_id,customer_name,seller_id,seller_name,status,reference,notes,created_by,created_at,updated_at,issuer_snapshot) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,customer.id,customer.name,u.id,u.name,'BORRADOR',input(b.reference,200),input(b.notes,1000),u.id,t,t,issuer),...products.map(x=>db.prepare('INSERT INTO dispatch_items VALUES(?,?,?,?,?,?)').bind(uuid(),id,x.id,x.name,x.unit,x.quantity))]);return json({id},201)}
 if(method==='POST'&&path[2]==='confirm'){let d=await detail(db,u,p,path[1]);if(d.seller_id!==u.id&&!has(p,'dispatch.read.all'))fail('Sin permiso',403);if(d.status!=='BORRADOR')fail('Estado inválido',409);let result=await db.batch([db.prepare('UPDATE dispatch_counter SET next_number=next_number+1 WHERE id=1 RETURNING next_number-1 AS number'),db.prepare("UPDATE dispatches SET status='CONFIRMADO',number=(SELECT next_number-1 FROM dispatch_counter WHERE id=1),confirmed_by=?,confirmed_at=?,updated_at=? WHERE id=? AND status='BORRADOR'").bind(u.id,now(),now(),d.id)]);return json({id:d.id,number:result[0].results[0].number})}
 if(method==='POST'&&path[2]==='void'){need(p,'dispatch.void');let d=await detail(db,u,p,path[1]);if(d.status!=='CONFIRMADO')fail('Estado inválido',409);await run(db,"UPDATE dispatches SET status='ANULADO',voided_by=?,voided_at=?,updated_at=? WHERE id=?",u.id,now(),now(),d.id);return json({ok:true})}
}
fail('Ruta inexistente',404)}
export default {async fetch(req,env){let c=cors(req,env);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:c});try{let r=await handler(req,env);Object.entries(c).forEach(([k,v])=>r.headers.set(k,v));r.headers.set('cache-control','no-store');return r}catch(e){return json({error:e.status?e.message:'Error interno'},e.status||500,c)}}};
