CREATE TABLE roles(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL);
CREATE TABLE permissions(name TEXT PRIMARY KEY);
CREATE TABLE role_permissions(role_id TEXT NOT NULL REFERENCES roles(id),permission TEXT NOT NULL REFERENCES permissions(name),PRIMARY KEY(role_id,permission));
CREATE TABLE users(id TEXT PRIMARY KEY,name TEXT NOT NULL,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,salt TEXT NOT NULL,role_id TEXT NOT NULL REFERENCES roles(id),active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE user_visibility(user_id TEXT NOT NULL REFERENCES users(id),seller_id TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(user_id,seller_id));
CREATE TABLE sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE categories(id TEXT PRIMARY KEY,name TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE products(id TEXT PRIMARY KEY,name TEXT NOT NULL,category_id TEXT REFERENCES categories(id),unit TEXT NOT NULL DEFAULT 'unidad',active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE customers(id TEXT PRIMARY KEY,name TEXT NOT NULL,phone TEXT,direction TEXT,notes TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE dispatch_counter(id INTEGER PRIMARY KEY CHECK(id=1),next_number INTEGER NOT NULL);
INSERT INTO dispatch_counter VALUES(1,1);
CREATE TABLE dispatches(id TEXT PRIMARY KEY,number INTEGER UNIQUE,customer_id TEXT NOT NULL REFERENCES customers(id),customer_name TEXT NOT NULL,seller_id TEXT NOT NULL REFERENCES users(id),seller_name TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('BORRADOR','CONFIRMADO','ANULADO')),reference TEXT,notes TEXT,created_by TEXT NOT NULL REFERENCES users(id),confirmed_by TEXT REFERENCES users(id),voided_by TEXT REFERENCES users(id),created_at TEXT NOT NULL,confirmed_at TEXT,voided_at TEXT,updated_at TEXT NOT NULL,issuer_snapshot TEXT);
CREATE TABLE dispatch_items(id TEXT PRIMARY KEY,dispatch_id TEXT NOT NULL REFERENCES dispatches(id),product_id TEXT NOT NULL REFERENCES products(id),product_name TEXT NOT NULL,unit TEXT NOT NULL,quantity REAL NOT NULL CHECK(quantity>0));
CREATE INDEX dispatch_seller_date ON dispatches(seller_id,created_at);
CREATE INDEX dispatch_customer ON dispatches(customer_id);
CREATE INDEX dispatch_item_product ON dispatch_items(product_id);
INSERT INTO roles VALUES('superadmin','superadmin'),('admin','admin'),('vendedor','vendedor'),('visor','visor');
INSERT INTO permissions VALUES('users.manage'),('roles.manage'),('catalog.manage'),('customers.manage'),('settings.manage'),('dispatch.create'),('dispatch.read.all'),('dispatch.void');
INSERT INTO role_permissions SELECT 'superadmin',name FROM permissions;
INSERT INTO role_permissions SELECT 'admin',name FROM permissions WHERE name!='roles.manage';
INSERT INTO role_permissions VALUES('vendedor','dispatch.create');
INSERT INTO settings VALUES('issuer','{"name":"","logo":"","direction":"","phone":"","extra":""}');
